defaults:
  -
    scope:
      path: "**/*.html"
    values:
      layout: "default"

mediaurl: "https://media.githubusercontent.com/media/learnrussian/learnrussian.github.io/master"
cssurl:   "https://media.githubusercontent.com/media/learnrussian/learnrussian.github.io/master/s/css/"
#baseurl: "/learnrussian.rt.com"
